### ISSUE TITLE
Support `file://` URLs

### ISSUE THREAD

**Issue by coreaidev** [guychauliac/maxxq-maven#103]
Currently it appears only http and https are supported, but it is common for users to have local maven repositories and would be good if the same API tools can be used there.

**Comment by guychauliac** [comment]
@coreaidev 

Hi,

thanks for your request.
Local file repositories are already supported by making use these implementations if IRepository:

LocalFileRepository: This one can be used to point to the local repository e.g. used by the local maven installation
FileCachingRepository: This one can be used in combination with another instanceof IRepository, e.g. RemoteRepository.  Once a maven pom is loaded from the remote repository it will store the pom in a local file location and next time retrieve it from this location.  

Gr
